diff id:000003,orig:evenodd.c -> id:000004,orig:hello.c
Src file: /root/tinycc/tcc.c
  New 'line' coverage: 333
Src file: /root/tinycc/libtcc.c
  New 'function' coverage: error1()
  New 'function' coverage: strcat_printf()
  New 'function' coverage: strcat_vprintf()
  New 'function' coverage: tcc_error()
  New 'function' coverage: tcc_warning()
  New 'line' coverage: 461
  New 'line' coverage: 464
  New 'line' coverage: 465
  New 'line' coverage: 466
  New 'line' coverage: 468
  New 'line' coverage: 471
  New 'line' coverage: 472
  New 'line' coverage: 473
  New 'line' coverage: 474
  New 'line' coverage: 476
  New 'line' coverage: 481
  New 'line' coverage: 483
  New 'line' coverage: 485
  New 'line' coverage: 486
  New 'line' coverage: 489
  New 'line' coverage: 490
  New 'line' coverage: 491
  New 'line' coverage: 499
  New 'line' coverage: 500
  New 'line' coverage: 502
  New 'line' coverage: 503
  New 'line' coverage: 505
  New 'line' coverage: 507
  New 'line' coverage: 510
  New 'line' coverage: 511
  New 'line' coverage: 512
  New 'line' coverage: 516
  New 'line' coverage: 517
  New 'line' coverage: 518
  New 'line' coverage: 538
  New 'line' coverage: 540
  New 'line' coverage: 543
  New 'line' coverage: 544
  New 'line' coverage: 545
  New 'line' coverage: 547
  New 'line' coverage: 548
  New 'line' coverage: 555
  New 'line' coverage: 557
  New 'line' coverage: 560
  New 'line' coverage: 563
  New 'line' coverage: 564
  New 'line' coverage: 565
Src file: /root/tinycc/tccgen.c
  New 'line' coverage: 4271
  New 'line' coverage: 4289
  New 'line' coverage: 4290
  New 'line' coverage: 4291
  New 'line' coverage: 7170
Src file: /root/tinycc/tccpp.c
  New 'function' coverage: expect()
  New 'line' coverage: 106
  New 'line' coverage: 108
  New 'line' coverage: 1995
  New 'line' coverage: 1997
  New 'line' coverage: 1999
  New 'line' coverage: 2002
  New 'line' coverage: 2003
  New 'line' coverage: 2004
  New 'line' coverage: 2005
